version: '2'

volumes:
  mongodb_data: { driver: local }

services:
  botpress:
    image: botpress/server:latest
    command: /botpress/bp --auto-migrate
    expose:
      - 3001
    environment:
      - DATABASE_URL=postgres://postgres:secretpw@postgres:5435/botpress_db
      - REDIS_URL=redis://redis:6379?password=redisPassword
      - EXTERNAL_URL=http://localhost:3001
      #- BP_MODULE_NLU_DUCKLINGURL=http://botpress_lang:8000
      #- BP_MODULE_NLU_LANGUAGESOURCES=[{"endpoint":"http://botpress_lang:3100"}]
      #- CLUSTER_ENABLED=true
      - BP_PRODUCTION=true
      - BPFS_STORAGE=database
    user: root
    depends_on:
      #- botpress_lang
      - postgres
      - redis
    volumes:
      - ./data/botpress/data:/botpress/data
    ports:
      - "3001:3000"

  # botpress_lang:
  #   image: botpress-lang
  #   command: bash -c "./duckling -p 8000 & ./bp lang --langDir /botpress/lang --port 3100"
  #   expose:
  #     - 3100
  #     - 8000
  #   volumes:
  #     - ./botpress/language:/botpress/lang

  postgres:
    image: postgres:14-alpine
    expose:
      - 5435
    ports:
      - "5435:5435"      
    environment:
      PGPORT: 5435
      POSTGRES_DB: botpress_db
      POSTGRES_PASSWORD: secretpw
      POSTGRES_USER: postgres
    volumes:
      - ./data/botpress/db:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    expose:
      - 6379
    command: redis-server --requirepass redisPassword
    volumes:
      - ./data/botpress/redisdb:/data

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"